-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/NewbieAndy/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
